from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class MasteryLevel(str, Enum):
    """How well the learner has grasped a concept."""

    UNKNOWN = "unknown"
    SEEN = "seen"           # has been exposed but not tested
    LEARNING = "learning"   # some correct, some wrong
    STABILIZING = "stabilizing"  # last N answers correct
    MASTERED = "mastered"   # consistently correct across contexts


@dataclass
class Option:
    """A single answer option."""

    key: str
    text: str


@dataclass
class Question:
    """A multiple-choice question generated by the tutor."""

    stem: str
    options: list[Option]
    correct_keys: list[str]


@dataclass
class TutorTurn:
    """One turn in the tutoring conversation.

    The tutor either presents a new question or wraps up the session.
    """

    question: Optional[Question] = None
    feedback: Optional[str] = None
    is_correct: Optional[bool] = None
    session_complete: bool = False
    summary: Optional[str] = None


@dataclass
class AnswerRecord:
    """A single answer the user gave."""

    stem: str
    chosen_keys: list[str]
    correct_keys: list[str]
    is_correct: bool
    feedback: str


@dataclass
class SessionState:
    """Persistent snapshot of a tutoring session."""

    session_id: str
    topic: str
    turn_count: int = 0
    correct_count: int = 0
    total_questions: int = 0
    answers: list[AnswerRecord] = field(default_factory=list)
    completed: bool = False
    summary: Optional[str] = None
